[package]
name = "aoc03"
version = "0.1.0"
authors = ["Paul Sbarra <Sbarra.Paul@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1"
regex = "1"